config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :back_tests, only: [:index, :new, :create, :edit]
  patch :clone_back_test, to: "back_tests#clone"

  resources :positions, only: [:index, :show]
  resources :strategies, only: [:index, :new, :create, :edit, :update]
  get :destroy_strategy, to: "strategies#destroy"

  get :positions_list_item_data, to: "positions#positions_list_item_data"
  get :price_history_for_position, to: "positions#price_history_for_position"

  get :run_back_test, to: "back_tests#run"

  get :destroy_back_test, to: "back_tests#destroy_back_test"
  get :stop_back_test, to: "back_tests#stop_back_test"
  get :back_tests_list_item_data, to: "back_tests#back_tests_list_item_data"
  get :profit_loss_series_for_back_test, to: "back_tests#profit_loss_series_for_back_test"
  get :profit_loss_bars_for_back_test, to: "back_tests#profit_loss_bars_for_back_test"
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  skip_forgery_protection
  def index
    @strategies = Strategy.all
  end

  def destroy
    strategy = Strategy.find(params[:strategy_id])
    strategy.destroy

    new_file_name = Rails.root.join("app", "strategies", "#{strategy.name.underscore}.rb")
    File.delete(new_file_name) {} if File.exists?(new_file_name)

    redirect_to strategies_path
  end

  def new
    @strategy = Strategy.new(
      relevant_candle_timeframes: ["m5", "h4"],
    )
  end

  def edit
    @strategy = Strategy.find(params[:id])
  end

  def create
    new_file_name = Rails.root.join("app", "strategies", "#{create_update_params[:name].underscore}.rb")
    unless File.exists?(new_file_name)
      File.open(new_file_name, "w+") do |f|
        content = File.read(Rails.root.join("lib", "strategies", "example_files", "strategy.rb.example"))
        content = content.gsub("<CLASS_NAME>", create_update_params[:name])

        candle_methods = create_update_params[:relevant_candle_timeframes].each_with_object("") do |tf, str|
          str << "  def update_#{tf}_candle_indicators(date_time:, symbol:)\n    \#@#{tf}_ema_50s[symbol] = indicators.ema(candles: @#{tf}_candles[symbol], period: 50).map(&:ema)\n    \#@#{tf}_ema_100s[symbol] = indicators.ema(candles: @#{tf}_candles[symbol], period: 100).map(&:ema)\n  end\n\n"
        end

        content = content.gsub("<CANDLE_INDICATOR_METHODS>", candle_methods)

        f.write(content)

        unless Object.const_defined?(create_update_params[:name])
          Object.class_eval(content, create_update_params[:name])
        end
      end
    end

    create_update_params[:name].constantize.find_or_create_by!(name: create_update_params[:name]) do |s|
      s.relevant_candle_timeframes = create_update_params[:relevant_candle_timeframes]
    end

    redirect_to strategies_path
  end

  private

  def create_update_params
    params.require(:strategy).permit(
      :name,
      relevant_candle_timeframes: []
    ).to_h.with_indifferent_access.tap do |h|
      h[:name] = h[:name].gsub(/-_/, " ").downcase.titleize.delete(" ")
      h[:relevant_candle_timeframes] = h[:relevant_candle_timeframes].reject { |e| e == "0" }
    end
  end
end

app/views/strategies/_create_new_strategy.html.erb
<div class="back-tests-run-new-test">
  <%= link_to(new_strategy_path)  do %>
    <div class="back-tests-run-new-test-icon-container">
      <div class="visible-corner left-visible-corner"></div>
      <div class="visible-corner right-visible-corner"></div>
      <div class="invisible-corner left-invisible-corner"></div>
      <div class="invisible-corner right-invisible-corner"></div>
      <%= image_tag("icons/plus-circle-icon.svg", class: "back-tests-run-new-test-icon") %>
    </div>
  <% end %>
</div>

app/views/strategies/_strategy_form.html.erb
<%= form_for strategy do |f| %>
  <div class="list-item">
    <div class="list-group-heading">
      Identification
    </div>
    <div class="list-row-item">
      <div class="list-item-k-v-section">
        <div class="list-item-k-v-section__key">
          <em>Strategy Name</em>
        </div>
        <div class="list-item-k-v-section__value">
          <%= f.text_field :name, class: "text-fields", required: true, value: strategy.name.present? ? strategy.name.split(/(?=[A-Z])/).join(" ") : "#{Faker::TvShows::DrWho.character} Strategy" %>
        </div>
      </div>
    </div>

    <div class="list-group-heading">
      Relevant Candle Timeframes
    </div>
    <div class="list-row-item wrappable select-options" data-controller="option-group">
      <% ["m5", "m15", "h1", "h2", "h4"].each do |tf| %>
        <div data-option-group-target="option"
             class="option-select-btn <%= "option-select-btn__active" if strategy.relevant_candle_timeframes.include?(tf) %>"
             data-action="click->option-group#optionClicked"
        >
          <%= f.check_box(:relevant_candle_timeframes, {id: "option-select-field", class: "hidden-element", multiple: true, checked: strategy.relevant_candle_timeframes.include?(tf)}, tf) %>

          <%=
            {
              "m5" => "5 Minute",
              "m15" => "15 Minute",
              "h1" => "1 Hour",
              "h2" => "2 Hour",
              "h4" => "4 Hour",
            }[tf]
          %>
        </div>
        <% if tf == "m15" %>
          <div class="vertical-divider"></div>
        <% end %>
      <% end %>
    </div>

    <div class="list-row-item">
      <%= f.submit class: "submit-btn" %>
    </div>
  </div>
<% end %>

app/views/strategies/edit.html.erb
<div class="page-title-text">Create New Strategy</div>
<div class="page-horizontal-divider"></div>

<div class="list-container">
  <%= render partial: "strategy_form", locals: { strategy: @strategy } %>
</div>

app/views/strategies/index.html.erb
<%= render partial: "create_new_strategy" %>

<div class="page-title-text">Strategies</div>
<div class="page-horizontal-divider"></div>

<div class="list-container">
  <% @strategies.each do |strategy| %>
    <div class="list-container">
      <div class="list-item">
        <div class="list-row-item">
          <%= strategy.name.titleize %>
          <%= link_to new_back_test_path(strategy_name: strategy.name) do %>
            <div>Run Back Test</div>
          <% end %>

          <%= link_to destroy_strategy_path(strategy_id: strategy.id) do %>
            <div>Delete</div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/strategies/new.html.erb
<div class="page-title-text">Create New Strategy</div>
<div class="page-horizontal-divider"></div>

<div class="list-container">
  <%= render partial: "strategy_form", locals: { strategy: @strategy } %>
</div>

<script type=application/javascript>
    function assetTypeBtnClicked(assetType) {
        let inputs = Array.from(document.getElementsByClassName(`symbol-option-btn-${assetType}`))
        let assetTypeBtn = document.getElementById(`asset-group-btn-${assetType}`)

        if (assetTypeBtn.dataset.enabled === "true") {
            assetTypeBtn.classList.remove("option-select-btn__active")
            assetTypeBtn.dataset.enabled = "false"
        } else {
            assetTypeBtn.classList.add("option-select-btn__active")
            assetTypeBtn.dataset.enabled = "true"
        }

        let shuffledInputs = inputs.sort(() => Math.random() - 0.5)

        for (let i = 0; i < shuffledInputs.length; i++) {
            setTimeout(function () {
                let input = shuffledInputs[i]
                let symbol = input.dataset.symbol
                let btn = document.getElementById(`symbol-select-btn-${symbol}`)

                if (assetTypeBtn.dataset.enabled === "false") {
                    input.checked = false
                    btn.classList.remove("option-select-btn__active")
                } else {
                    input.checked = true
                    btn.classList.add("option-select-btn__active")
                }
            }, i*10)
        }
    }
</script>