config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :back_tests, only: [:index, :new, :create, :edit]
  patch :clone_back_test, to: "back_tests#clone"

  resources :positions, only: [:index, :show]
  resources :strategies, only: [:index, :new, :create, :edit, :update]
  get :destroy_strategy, to: "strategies#destroy"

  get :positions_list_item_data, to: "positions#positions_list_item_data"
  get :price_history_for_position, to: "positions#price_history_for_position"

  get :run_back_test, to: "back_tests#run"

  get :destroy_back_test, to: "back_tests#destroy_back_test"
  get :stop_back_test, to: "back_tests#stop_back_test"
  get :back_tests_list_item_data, to: "back_tests#back_tests_list_item_data"
  get :profit_loss_series_for_back_test, to: "back_tests#profit_loss_series_for_back_test"
  get :profit_loss_bars_for_back_test, to: "back_tests#profit_loss_bars_for_back_test"
end

app/models/back_test.rb
class BackTest < ApplicationRecord
  include ActionView::Helpers::DateHelper
  class InvalidProgressDateError < StandardError; end

  default_scope -> { where(destroying: false) }

  scope :running, -> { where(ended_at: nil) }
  scope :complete, -> { where.not(ended_at: nil) }

  validates_presence_of :strategy_class

  belongs_to :strategy, polymorphic: true

  after_create :create_account

  STATE_READY = "state_ready"
  STATE_RUNNING = "state_running"
  STATE_MANUALLY_FINISHED = "state_manually_finished"
  STATE_ORGANICALLY_FINISHED = "state_organically_finished"
  STATE_EXCEPTION = "state_exception"

  POSITION_PLACEMENT_STRATEGY_MARKET = "market"
  POSITION_PLACEMENT_STRATEGY_STOP = "stop"
  POSITION_PLACEMENT_STRATEGY_LIMIT = "limit"

  DEFAULT_RISK_PCT = 1
  DEFAULT_COMMISSION_PCT = 3.5
  DEFAULT_SYMBOLS = ["AUDCAD", "MSFT"]
  DEFAULT_START_DATE = DateTime.parse("2018-01-01")
  DEFAULT_END_DATE = DateTime.parse("2019-01-01")
  DEFAULT_TRAIL_STOPS = true
  DEFAULT_BREAK_EVEN = false
  DEFAULT_TARGET_PROFIT_TO_LOSS_RATIO = 2
  DEFAULT_PENDING_POSITION_EXPIRY_PERIOD = 2.hours
  DEFAULT_TAKE_PROFIT = true
  DEFAULT_MAX_SPREAD = 2.0
  DEFAULT_STARTING_BALANCE = 20000.0
  DEFAULT_TICKS_PROCESSED_IN_PERIOD = []
  DEFAULT_POSITION_PLACEMENT_STRATEGY = POSITION_PLACEMENT_STRATEGY_MARKET


  attribute :risk_pct, default: DEFAULT_RISK_PCT
  attribute :commission_pct, default: DEFAULT_COMMISSION_PCT
  attribute :symbols, default: DEFAULT_SYMBOLS
  attribute :start_date, default: DEFAULT_START_DATE
  attribute :end_date, default: DEFAULT_END_DATE
  attribute :ended_at, default: nil
  attribute :trail_stops, default: DEFAULT_TRAIL_STOPS
  attribute :break_even, default: DEFAULT_BREAK_EVEN
  attribute :take_profit, default: DEFAULT_TAKE_PROFIT
  attribute :destroying, default: false
  attribute :target_profit_to_loss_ratio, default: DEFAULT_TARGET_PROFIT_TO_LOSS_RATIO
  attribute :pending_position_expiry_period, default: DEFAULT_PENDING_POSITION_EXPIRY_PERIOD
  attribute :progress_date, default: DEFAULT_START_DATE
  attribute :max_spread, default: DEFAULT_MAX_SPREAD
  attribute :starting_balance, default: DEFAULT_STARTING_BALANCE
  attribute :ticks_processed_in_period, default: DEFAULT_TICKS_PROCESSED_IN_PERIOD
  attribute :position_placement_strategy, default: DEFAULT_POSITION_PLACEMENT_STRATEGY

  FINISHED_STATES = [STATE_MANUALLY_FINISHED, STATE_ORGANICALLY_FINISHED, STATE_EXCEPTION]

  has_many :positions, dependent: :destroy
  belongs_to :back_test_account, class_name: "Accounts::BackTestAccount", dependent: :destroy, optional: true

  def run!
    update(state: STATE_RUNNING)
    strategy.run!(back_test: self)
  end

  def account
    back_test_account
  end

  def unrealised_profit_loss
    return 0.0 if positions.open.empty?

    positions.open.pluck(:gross_profit).sum
  end

  def finished?
    FINISHED_STATES.include?(state)
  end

  def running?
    !finished?
  end

  def manually_finish!
    update(ended_at: DateTime.now, state: STATE_MANUALLY_FINISHED)
  end

  def organically_finish!
    update(ended_at: DateTime.now, state: STATE_ORGANICALLY_FINISHED)
  end

  def exception_finish!
    update(ended_at: DateTime.now, state: STATE_EXCEPTION)
  end

  def created_at_readable
    day = created_at.strftime("%-d").to_i.ordinalize

    created_at.strftime("#{day} %b %Y at %T")
  end

  def return_as_pct
    return 0.0 unless back_test_account.present?
    (((account.current_balance - account.starting_balance) / account.starting_balance) * 100).round(2)
  end

  def average_return
    return 0 unless positions.closed.any?
    positions.closed.pluck(:gross_profit).sum.to_f/positions.closed.count
  end

  def average_win
    return 0 unless positions.wins.any?
    positions.wins.pluck(:gross_profit).sum.to_f/positions.wins.count
  end

  def average_loss
    return 0 unless positions.losses.any?
    positions.losses.pluck(:gross_profit).sum.to_f/positions.losses.count
  end

  def set_progress(progress_date:)
    raise InvalidProgressDateError, "Progress date is before the start date" if progress_date < start_date
    update(progress_date: progress_date)
  end

  def progress_as_pct
    return 0.0 if progress_date.nil?

    total_days = (end_date - start_date).to_f
    current_days = (progress_date - start_date).to_f

    ((current_days / total_days) * 100).round(2)
  end

  def seconds_elapsed
    DateTime.now.to_i - created_at.to_i
  end

  def life_time
    if running?
      DateTime.now.to_i - created_at.to_i
    else
      ended_at.to_i - created_at.to_i
    end
  end

  def estimated_finish_time
    return 0.0 if progress_as_pct == 0.0

    fraction_complete = (100.0/progress_as_pct)
    estimated_time_seconds = fraction_complete * seconds_elapsed
    seconds_left = estimated_time_seconds - seconds_elapsed

    created_at + seconds_left.seconds
  end

  def estimated_time_left
    return "calculating..." if progress_as_pct == 0.0
    distance_of_time_in_words(created_at, estimated_finish_time, include_minutes: true, include_seconds: true)
  end

  def pct_changes
    @pct_changes ||= positions.closed.map(&:pct_change)
  end

  def mean_pct_change
    pct_changes.mean
  end

  def std_dev_pct_changes
    pct_changes.stdev
  end

  def sharpe_ratio
    return 0.0 unless positions.closed.any?

    mean_pct_change/std_dev_pct_changes
  end

  def create_account
    Accounts::BackTestAccount.create!(back_test: self, starting_balance: starting_balance)
  end
end

app/controllers/back_tests_controller.rb
class BackTestsController < ApplicationController
  def index
    @back_tests = BackTest.all
  end
  def new
    @back_test = BackTest.new
  end

  def edit
    @back_test = BackTest.find(params[:id])
  end

  def clone
    # back_test = BackTest.find(params[:id])
    new_back_test = create_back_test
    BackTestRunner.perform_later(back_test_id: new_back_test.id)

    if params[:destroy_existing] == "true"
      BackTest.find(params[:id]).destroy
    end

    redirect_to back_tests_path
  end

  def create
    back_test = create_back_test

    BackTestRunner.perform_later(back_test_id: back_test.id)

    redirect_to back_tests_path
  end

  def run
    redirect_to back_tests_path
  end

  def create_back_test
    strategy_class = create_update_params[:strategy_class]
    BackTest.create!(
      create_update_params.merge(
        {
          strategy_type: strategy_class,
          strategy_id: strategy_class.constantize.find_by(
            name: strategy_class
          ).id
        }
      )
    ).tap do |bt|
      bt.state = BackTest::STATE_READY
    end
  end

  def destroy_back_test
    bt = BackTest.find(params[:id])
    bt.update(destroying: true)
    redirect_to back_tests_path
  end

  def stop_back_test
    BackTest.find(params[:id]).manually_finish!
    redirect_to back_tests_path
  end

  def back_tests_list_item_data
    start = DateTime.now
    back_test = BackTest.find(params[:id])

    back_test_representation = {
      id: back_test.id,
      name: back_test.strategy_class.split(/(?=[A-Z])/).join(" ").titleize,
      started_at_readable: "#{back_test.id} - Started on #{back_test.created_at_readable}",
      balance_pct_change: "#{back_test.return_as_pct >= 0 ? "+" : "-"} #{back_test.return_as_pct.abs} %",
      starting_balance: ActionController::Base.helpers.number_to_currency(back_test.account&.starting_balance, unit: "£"),
      current_balance: ActionController::Base.helpers.number_to_currency(back_test.account&.current_balance, unit: "£"),
      net_balance: "(#{ActionController::Base.helpers.number_to_currency(back_test.account&.current_balance(net: true), unit: "£")})",
      profit_loss: ActionController::Base.helpers.number_to_currency(back_test.account&.current_balance - back_test.account&.starting_balance, unit: "£"),
      net_profit_loss: "(#{ActionController::Base.helpers.number_to_currency(back_test.account&.current_balance(net: true) - back_test.account&.starting_balance, unit: "£")})",
      time_elapsed: ActionController::Base.helpers.distance_of_time_in_words(back_test.life_time),
      time_remaining: back_test.estimated_time_left,
      model_progress: back_test.progress_date.present? ? "#{ActionController::Base.helpers.distance_of_time_in_words((back_test.progress_date&.to_i - back_test.start_date.to_i))}" : "Calculating...",
      model_period: ActionController::Base.helpers.distance_of_time_in_words((back_test.end_date.to_i - back_test.start_date.to_i)),
      pct_complete: "#{back_test.progress_as_pct}%",
      mean_pct_returns: "#{back_test.mean_pct_change.round(4)}%",
      std_dev: back_test.std_dev_pct_changes.round(4) || 0.0,
      sharpe_ratio: back_test.sharpe_ratio.round(4),
      total_position_count: back_test.positions.open.count +  back_test.positions.closed.count,
      open_position_count: back_test.positions.open.count,
      unrealised_pl: ActionController::Base.helpers.number_to_currency(back_test.unrealised_profit_loss, unit: "£"),
      wins_count: back_test.positions.closed.wins.count,
      wins_pct: "(#{((back_test.positions.wins.count.to_f/back_test.positions.closed.count) * 100).round(2)}%)",
      losses_count: back_test.positions.closed.losses.count,
      losses_pct: "(#{((back_test.positions.losses.count.to_f/back_test.positions.closed.count) * 100).round(2)}%)",
      avg_return: ActionController::Base.helpers.number_to_currency(back_test.average_return, unit: "£"),
      avg_win: ActionController::Base.helpers.number_to_currency(back_test.average_win, unit: "£"),
      avg_loss: ActionController::Base.helpers.number_to_currency(back_test.average_loss, unit: "£"),
      average_total_tick_time_series: back_test.ticks_processed_in_period.map { |d| d["time_taken"].to_f/10000 },
      average_skipped_tick_time_series: back_test.ticks_processed_in_period.map { |d| d["ticks_skipped"].to_f },
      average_processed_tick_time_series: back_test.ticks_processed_in_period.map { |d| d["ticks_processed"].to_f }
    }

    render json: back_test_representation
  end

  def profit_loss_series_for_back_test
    running_gross_balance = [0]
    running_net_balance = [0]


    BackTest.find(params[:id]).positions.closed.order(:closed_at).each do |pos|
      running_gross_balance << pos.gross_profit + running_gross_balance.last
      running_net_balance << pos.net_profit + running_net_balance.last
    end

    render json: { html: [{name: "Running Gross Balance", data: running_gross_balance}, {name: "Running Net Balance", data: running_net_balance}] }
  end

  def profit_loss_bars_for_back_test
    data = [
      {
        x: "Winnings",
        y: BackTest.find(params[:id]).positions.wins.pluck(:gross_profit).sum
      },
      {
        x: "Losses",
        y: BackTest.find(params[:id]).positions.losses.pluck(:gross_profit).map(&:abs).sum
      }
    ]

    render json: { html: [{name: "Profit vs Loss", data: data}] }
  end

  private

  def create_update_params
    params.require(:back_test).permit(
      :strategy_class,
      :start_date,
      :end_date,
      :starting_balance,
      :risk_pct,
      :commission_pct,
      :position_placement_strategy,
      symbols: [],
    ).to_h.with_indifferent_access.tap do |h|
      h[:symbols] = h[:symbols].reject { |e| e == "0" }
    end
  end
end

app/views/back_tests/_back_tests_list.html.erb
<% back_tests.reverse.each do |bt| %>
  <div id="back-test-data-container" class="vertical-split-container">
    <div
      class="back-test-list-item-container"
      data-controller="back-test-list-item"
      data-back-test-list-item-back-test-id="<%= bt.id %>"
    >
      <%=  render partial: "back_tests/back_tests_list_item", locals: {bt: bt} %>
    </div>

    <div class="utility-icon-container">
      <div class="utility-icon-div">
        <%= link_to(image_tag("icons/trash-icon.svg", class: "utility-icon-img"), destroy_back_test_path(id: bt.id)) %>
      </div>

      <% if bt.finished? %>
        <div class="utility-icon-div">
          <%= link_to(image_tag("icons/copy-icon.svg", class: "utility-icon-img"), edit_back_test_path(bt)) %>
        </div>
      <% else %>
        <div class="utility-icon-div">
          <%= link_to(stop_back_test_path(id: bt.id)) do %>
            <div class="black-square"></div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/back_tests/_back_tests_list_item.html.erb
<div class="list-item">
  <div class="list-row-item">
    <div class="back-test-icon-div">
      <img src="<%= image_path("icons/bar-chart-icon.svg") %>" class="back-test-icon-img" />
    </div>

    <div class="back-test-strategy-k-v-section list-item-k-v-section__value--bold">
      <span id="name-container" style="font-size: 1.3rem;"></span><br>
      <span id="started-at-readable-container" style="display: inline-block; font-size: 0.87rem; opacity: 0.7; margin-top: 3px;"></span>
    </div>

    <div id="balance-pct-change-container" class="list-item-k-v-section__value list-item-k-v-section__value--bold">
    </div>
  </div>

  <div class="back-test-symbol-list-container" style="overflow: hidden">
    <% bt.symbols.each do |symbol| %>
      <div class="back-test-symbol-list-item">
        <%= symbol %>
      </div>
    <% end %>
  </div>

  <div class="list-group-heading">
    Performance Overview
  </div>


  <div class="list-row-item">
    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Starting Balance</em>
      </div>
      <div class="list-item-k-v-section__value">
        <strong id="starting-balance-container"></strong>
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Current Balance</em>
      </div>
      <div class="list-item-k-v-section__value">
        <strong id="current-balance-container"></strong> <span id="net-balance-container"></span>
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Profit/Loss</em>
      </div>
      <div class="list-item-k-v-section__value">
        <strong id="profit-loss-container"></strong> <span id="net-profit-loss-container"></span>
      </div>
    </div>

    <div class="vertical-divider">&nbsp;</div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Time Elapsed</em>
      </div>
      <div id="time-elapsed-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Time Remaining</em>
      </div>
      <div id="time-remaining-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="vertical-divider">&nbsp;</div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Period To Model</em>
      </div>
      <div id="model-period-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Current Model Progress</em>
      </div>
      <div id="model-progress-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Percent Complete</em>
      </div>
      <div id="pct-complete-container" class="list-item-k-v-section__value">
      </div>
    </div>
  </div>



  <div class="list-group-heading">
    Feasibility
  </div>

  <div class="list-row-item">
    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Mean Pct Return</em>
      </div>
      <div id="mean-pct-returns-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Standard Deviation</em>
      </div>
      <div id="std-dev-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Sharpe Ratio</em>
      </div>
      <div id="sharpe-ratio-container" class="list-item-k-v-section__value">
      </div>
    </div>
  </div>



  <div class="list-group-heading">
    <%= link_to "Positions", positions_path(back_test_id: bt.id) %>
  </div>

  <div id="list-row-item-bar-<%= bt.id %>" class="list-row-item">
    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Total Positions</em>
      </div>
      <div id="total-position-count-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="vertical-divider">&nbsp;</div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Open Positions</em>
      </div>
      <div id="open-position-count-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Unrealised P/L</em>
      </div>
      <div id="unrealised-pl-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="vertical-divider">&nbsp;</div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Wins</em>
      </div>
      <div class="list-item-k-v-section__value">
        <span id="wins-count-container"></span> <span style="font-size: 0.75rem"><em id="wins-pct-container"></em></span>
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Losses</em>
      </div>
      <div class="list-item-k-v-section__value">
        <span id="losses-count-container"></span> <span style="font-size: 0.75rem"><em id="losses-pct-container"></em></span>
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Average Return</em>
      </div>
      <div id="avg-return-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Average Win</em>
      </div>
      <div id="avg-win-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="list-item-k-v-section">
      <div class="list-item-k-v-section__key">
        <em>Average Loss</em>
      </div>
      <div id="avg-loss-container" class="list-item-k-v-section__value">
      </div>
    </div>

    <div class="vertical-divider">&nbsp;</div>

    <div id="profit-loss-bar-chart-container-<%= bt.id %>" class="profit-loss-bar-chart-container" style="flex-grow: 1">
    </div>
  </div>

  <div class="list-group-heading">
    Profit/Loss
  </div>

  <div id="list-row-item-area-<%= bt.id %>" class="list-row-item">
    <div id="profit-loss-area-chart-container-<%= bt.id %>" class="chart-container" data-back-test-list-item-area-chart-target style="flex-grow: 1">
    </div>
  </div>

  <div class="list-group-heading">
    Application Performance
  </div>

  <div id="list-row-item-area-<%= bt.id %>" class="list-row-item">
    <div id="average-tick-time-chart-container-<%= bt.id %>" class="chart-container" data-back-test-list-item-area-chart-target style="flex-grow: 1">
    </div>
  </div>
</div>

app/views/back_tests/_run_new_test.html.erb
<div class="back-tests-run-new-test">
  <%= link_to(strategies_path)  do %>
    <div class="back-tests-run-new-test-icon-container">
      <div class="visible-corner left-visible-corner"></div>
      <div class="visible-corner right-visible-corner"></div>
      <div class="invisible-corner left-invisible-corner"></div>
      <div class="invisible-corner right-invisible-corner"></div>
      <%= image_tag("icons/plus-circle-icon.svg", class: "back-tests-run-new-test-icon") %>
    </div>
  <% end %>
</div>

app/views/back_tests/edit.html.erb
<div class="page-title-text">Edit BackTest</div>
<div class="page-horizontal-divider"></div>

<div class="list-container">
  <%= form_for @back_test, url: clone_back_test_path(id: @back_test.id) do |f| %>
    <%= hidden_field_tag(:destroy_existing, false) %>
    <div class="list-item">
      <%= render partial: "back_test_form", locals: { back_test: @back_test, f: f } %>

      <div class="list-row-item">
        <%= f.submit "Relaunch Back Test with New Parameters", class: "submit-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/back_tests/index.html.erb
<%= render partial: "run_new_test" %>
<div class="page-title-text">Back Tests</div>
<div class="page-horizontal-divider"></div>

<div class="list-container" id="back-test-list-container">
  <%=  render partial: "back_tests/back_tests_list", locals: {back_tests: @back_tests} %>
</div>

app/views/back_tests/new.html.erb
<div class="page-title-text">Create BackTest</div>
<div class="page-horizontal-divider"></div>

<div class="list-container">
  <%= form_for @back_test do |f| %>
    <div class="list-item">
      <%= render partial: "back_test_form", locals: { back_test: @back_test, f: f } %>

      <div class="list-row-item">
        <%= f.submit class: "submit-btn" %>
      </div>
    </div>
  <% end %>
</div>